<a href="https://colab.research.google.com/github/heavy1368/ON2022/blob/main/Lab6_on_live.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Algebra liniowa w Pythonie
* ```np.linalg.inv ``` - odwrotność macierzy
* ```np.linalg.det``` - wyznacznik
* ```np.linalg.eig``` - wartości i wektory własne
* ```np.dot``` - iloczyn macierzowy
* ```np.inner``` - iloczyn skalarny
* ```np.corss``` - iloczyn wektorowy

* ```np.linalg.norm``` - norma macierzy lub wektora

In [1]:
import numpy as np

In [ ]:
A=np.array([[2,3],[0,2]])
B=np.array([[2,5],[3,8]])
C=np.dot(B,np.dot(A,np.linalg.inv(B)))
Eigenvalues=np.linalg.eig(A)


In [ ]:
np.max(Eigenvalues[0])

2.0

#### Zad.1
Macierze o wartościach własnych 1,2


In [ ]:
B=np.array([[1,2],[3,4]])

In [ ]:
np.linalg.det(B)

-2.0000000000000004

In [ ]:
C=np.dot(B,np.dot(np.diag([1,2]),np.linalg.inv(B)))

In [ ]:
np.linalg.eig(C)

(array([2., 1.]), array([[0.4472136 , 0.31622777],
        [0.89442719, 0.9486833 ]]))

In [ ]:
B @ B 

array([[ 7, 10],
       [15, 22]])

In [ ]:
np.dot(B,B)

array([[ 7, 10],
       [15, 22]])

#### Rozkłady macierzy
* ```np.linalg.eig``` - to właściwie rozkład Jordana (macierz kwadratowa)
* ```np.linalg.svd``` - rozkład SVD (ortogonalna, diagonalna, ortogonalna)
* ```np.linalg.qr``` - rozkład QR (ortogonalna, górnotrójkątna)
* ```scipy.linalg.lu``` - rozkład LU (dolnotrójkątna, górnotrójkątna)

#### Zadanie 2: SVD



In [ ]:
A=np.random.random((5,5))
A

array([[0.37480706, 0.1869102 , 0.88450454, 0.27218647, 0.60516631],
       [0.33508562, 0.25855324, 0.11685219, 0.29841565, 0.45549406],
       [0.11779211, 0.08722226, 0.87930126, 0.9910624 , 0.31765611],
       [0.95482542, 0.52510547, 0.43718157, 0.7524423 , 0.23630132],
       [0.17152261, 0.83530153, 0.70537941, 0.08963202, 0.36817803]])

In [ ]:
SVD=np.linalg.svd(A)


In [ ]:
SVD[0] @ np.diag(SVD[1]) @ SVD[2]-A

array([[-1.11022302e-16, -5.55111512e-16, -7.77156117e-16,
        -3.88578059e-16, -5.55111512e-16],
       [ 0.00000000e+00, -2.22044605e-16,  1.52655666e-16,
        -1.11022302e-16,  5.55111512e-17],
       [-1.80411242e-16,  6.80011603e-16,  0.00000000e+00,
        -3.33066907e-16,  1.66533454e-16],
       [-2.22044605e-16, -1.11022302e-16, -2.77555756e-16,
        -4.44089210e-16, -3.60822483e-16],
       [ 1.11022302e-16, -3.33066907e-16, -4.44089210e-16,
         4.71844785e-16, -1.66533454e-16]])

In [ ]:
(SVD[0] @ SVD[0].T).round(0)

array([[ 1.,  0., -0., -0., -0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [-0.,  0.,  1.,  0.,  0.],
       [-0.,  0.,  0.,  1.,  0.],
       [-0.,  0.,  0.,  0.,  1.]])

#### Zadanie
Znajdź rozkład własny i rozkład SVD macierzy $\begin{bmatrix} 1&2&3\\1&2&1\\0&1&0\end{bmatrix}$.

In [ ]:
np.concatenate([A,A])

array([[0.37480706, 0.1869102 , 0.88450454, 0.27218647, 0.60516631],
       [0.33508562, 0.25855324, 0.11685219, 0.29841565, 0.45549406],
       [0.11779211, 0.08722226, 0.87930126, 0.9910624 , 0.31765611],
       [0.95482542, 0.52510547, 0.43718157, 0.7524423 , 0.23630132],
       [0.17152261, 0.83530153, 0.70537941, 0.08963202, 0.36817803],
       [0.37480706, 0.1869102 , 0.88450454, 0.27218647, 0.60516631],
       [0.33508562, 0.25855324, 0.11685219, 0.29841565, 0.45549406],
       [0.11779211, 0.08722226, 0.87930126, 0.9910624 , 0.31765611],
       [0.95482542, 0.52510547, 0.43718157, 0.7524423 , 0.23630132],
       [0.17152261, 0.83530153, 0.70537941, 0.08963202, 0.36817803]])

In [ ]:
B=np.array([[1,2,3],[1,2,1]])

In [ ]:
B_SVD=np.linalg.svd(B)

In [ ]:
sigma=np.diag(B_SVD[1])
sigma

array([[4.3525018, 0.       ],
       [0.       , 1.0274863]])

In [ ]:
sigma2=np.concatenate([sigma,np.zeros((2,1))],axis=1)

In [ ]:
sigma2

array([[4.3525018, 0.       , 0.       ],
       [0.       , 1.0274863, 0.       ]])

In [ ]:
B_SVD[0] @ sigma2 @ B_SVD[2]

array([[1., 2., 3.],
       [1., 2., 1.]])

#### Zadanie
Oblicz $\begin{bmatrix} 1&2&3\\1&2&1\\0&1&0\end{bmatrix}^{20}$.

In [ ]:
A=np.array([[1,2,3],[1,2,1],[0,1,0]])

In [ ]:
%time np.linalg.matrix_power(A,20)

CPU times: user 90 µs, sys: 8 µs, total: 98 µs
Wall time: 101 µs


array([[16968908951, 41687151125, 26786952325],
       [14535850675, 35709909551, 22946150525],
       [ 4205149925, 10330700750,  6638208201]])

In [ ]:
%%time
A_rozklad=np.linalg.eig(A)
JA=np.diag(A_rozklad[0])
P=A_rozklad[1]
P @ JA**20 @ np.linalg.inv(P)


CPU times: user 571 µs, sys: 0 ns, total: 571 µs
Wall time: 540 µs


array([[ 3.45667834+0.j        ,  0.        +0.j        ,
         0.        +0.j        ],
       [ 0.        +0.j        , -0.22833917+0.72556968j,
         0.        +0.j        ],
       [ 0.        +0.j        ,  0.        +0.j        ,
        -0.22833917-0.72556968j]])

In [ ]:

P

array([[ 0.74635087+0.j        , -0.85289345+0.j        ,
        -0.85289345-0.j        ],
       [ 0.63933662+0.j        ,  0.21479077+0.23188188j,
         0.21479077-0.23188188j],
       [ 0.18495693+0.j        ,  0.20602029-0.36086579j,
         0.20602029+0.36086579j]])

## Rozwiązywanie układów równań

* ```np.linalg.cond``` - wskaźnik uwarunkowania
* ```np.linalg.solve``` - rozwiązywanie

In [ ]:
np.linalg.cond(A)

11.87432495287239

SyntaxError: ignored

#### Zadanie 
Oblicz współczynnik uwarunkowania i rozwiąż układ równań $Ax=b$.

$$
A=\begin{bmatrix} 1&0&2\\3&2&1\\1&1&1 \end{bmatrix},\quad b_1=\begin{bmatrix}20.001\\-9.9999\\ 100.00001\end{bmatrix},\quad  b_2=\begin{bmatrix}20\\-10\\ 100\end{bmatrix}
$$

In [ ]:
A=np.array([[1,0,2],[3,2,1],[1,1,1]])

In [ ]:
np.linalg.cond(A)

10.617346008950063

In [ ]:
b1=np.array([20.001,-9.9999,100.00001])
b2=np.array([20,-10,100])

In [ ]:
np.linalg.solve(A,b1)

array([-133.33294667,  156.66598333,   76.66697333])

In [ ]:
np.linalg.solve(A,b2)

array([-133.33333333,  156.66666667,   76.66666667])

### Zadanie domowe
Stowrzyć macierz 3x3 o współczynniku uwarunkowania co najmniej $10000$ i sprawdzić błąd rozwiązania dla b1 i b2

In [19]:
import numpy as np
A=np.array([[1,131313,2],[3,2,1],[1,1,1]])


In [20]:
np.linalg.cond(A)

224165.98962784297

In [21]:
b1=np.array([20.001,-9.9999,100.00001])
b2=np.array([20,-10,100])

In [22]:
j=np.linalg.solve(A,b1)

In [23]:
k=np.linalg.solve(A,b2)

In [24]:
j

array([-5.49990602e+01, -1.78962981e-03,  1.55000860e+02])

In [25]:
k

array([-5.49991052e+01, -1.78963762e-03,  1.55000895e+02])

In [26]:
np.abs(j-k)

array([4.49960971e-05, 7.80586620e-09, 3.50039030e-05])

#### Zadanie dla chętnych (łańcuch Markowa)
$P=\begin{bmatrix} 1&0&0&0&0&0\\0&1&0&0&0&0\\p&q&r&0&0&0\\p&0&q&r&0&0\\p&0&0&q&r&0\\p&0&0&0&q&r \end{bmatrix}$



Macierz P opisuje prawdopodobieństwa przejść między pięcioma stanami: wyrzucony ze studiów, ukończył studia, po 4 roku, po 3 roku, po 2 roku, po 1 roku. (np. ze stanu nr 6 do stanu nr 5 prawdop. = q). Przyjmijmy p=0.2, q=0.7, r=0.1.

* Oblicz prawdopodobieństwo, że jeśli ukończyłeś pierwszy rok, to ukończysz całe studia.

* Zauważ w macierzy $P$ blokową strukturę: $P=\begin{bmatrix} Id & 0 \\ R & Q \end{bmatrix}$. Porównaj poprzedni wynik z wynikiem mnożenia $(Id-Q)^{-1} R$.