<a href="https://colab.research.google.com/github/heavy1368/ON2022/blob/main/Lab6_on_live.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Algebra liniowa w Pythonie
* ```np.linalg.inv ``` - odwrotność macierzy
* ```np.linalg.det``` - wyznacznik
* ```np.linalg.eig``` - wartości i wektory własne
* ```np.dot``` - iloczyn macierzowy
* ```np.inner``` - iloczyn skalarny
* ```np.corss``` - iloczyn wektorowy

* ```np.linalg.norm``` - norma macierzy lub wektora

In [2]:
import numpy as np

In [ ]:
A=np.array([[2,3],[0,2]])
B=np.array([[2,5],[3,8]])
C=np.dot(B,np.dot(A,np.linalg.inv(B)))
Eigenvalues=np.linalg.eig(A)


In [ ]:
np.max(Eigenvalues[0])

2.0

#### Zad.1
Macierze o wartościach własnych 1,2


In [ ]:
B=np.array([[1,2],[3,4]])

In [ ]:
np.linalg.det(B)

-2.0000000000000004

In [ ]:
C=np.dot(B,np.dot(np.diag([1,2]),np.linalg.inv(B)))

In [ ]:
np.linalg.eig(C)

(array([2., 1.]), array([[0.4472136 , 0.31622777],
        [0.89442719, 0.9486833 ]]))

In [ ]:
B @ B 

array([[ 7, 10],
       [15, 22]])

In [ ]:
np.dot(B,B)

array([[ 7, 10],
       [15, 22]])

#### Rozkłady macierzy
* ```np.linalg.eig``` - to właściwie rozkład Jordana (macierz kwadratowa)
* ```np.linalg.svd``` - rozkład SVD (ortogonalna, diagonalna, ortogonalna)
* ```np.linalg.qr``` - rozkład QR (ortogonalna, górnotrójkątna)
* ```scipy.linalg.lu``` - rozkład LU (dolnotrójkątna, górnotrójkątna)

#### Zadanie 2: SVD



In [3]:
A=np.random.random((5,5))
A

array([[0.26264994, 0.6307768 , 0.60695765, 0.89779895, 0.5981683 ],
       [0.89035457, 0.31590805, 0.93872136, 0.85634261, 0.20626838],
       [0.97059254, 0.99613507, 0.31631608, 0.64751173, 0.16604405],
       [0.83923616, 0.54128446, 0.13165453, 0.39099149, 0.6188132 ],
       [0.91735061, 0.49358508, 0.89708025, 0.11717791, 0.03696034]])

In [4]:
SVD=np.linalg.svd(A)


In [5]:
SVD[0] @ np.diag(SVD[1]) @ SVD[2]-A

array([[ 6.10622664e-16, -1.11022302e-16,  5.55111512e-16,
         2.22044605e-16,  3.33066907e-16],
       [ 5.55111512e-16,  4.44089210e-16,  5.55111512e-16,
         6.66133815e-16,  3.33066907e-16],
       [ 5.55111512e-16,  3.33066907e-16,  5.55111512e-16,
         5.55111512e-16,  1.38777878e-16],
       [ 1.11022302e-16,  3.33066907e-16,  6.66133815e-16,
         1.11022302e-16, -1.11022302e-16],
       [ 1.11022302e-16,  1.11022302e-16,  2.22044605e-16,
         5.82867088e-16,  4.85722573e-16]])

In [6]:
(SVD[0] @ SVD[0].T).round(0)

array([[ 1., -0.,  0., -0.,  0.],
       [-0.,  1.,  0.,  0., -0.],
       [ 0.,  0.,  1., -0., -0.],
       [-0.,  0., -0.,  1.,  0.],
       [ 0., -0., -0.,  0.,  1.]])

#### Zadanie
Znajdź rozkład własny i rozkład SVD macierzy $\begin{bmatrix} 1&2&3\\1&2&1\\0&1&0\end{bmatrix}$.

In [ ]:
np.concatenate([A,A])

array([[0.37480706, 0.1869102 , 0.88450454, 0.27218647, 0.60516631],
       [0.33508562, 0.25855324, 0.11685219, 0.29841565, 0.45549406],
       [0.11779211, 0.08722226, 0.87930126, 0.9910624 , 0.31765611],
       [0.95482542, 0.52510547, 0.43718157, 0.7524423 , 0.23630132],
       [0.17152261, 0.83530153, 0.70537941, 0.08963202, 0.36817803],
       [0.37480706, 0.1869102 , 0.88450454, 0.27218647, 0.60516631],
       [0.33508562, 0.25855324, 0.11685219, 0.29841565, 0.45549406],
       [0.11779211, 0.08722226, 0.87930126, 0.9910624 , 0.31765611],
       [0.95482542, 0.52510547, 0.43718157, 0.7524423 , 0.23630132],
       [0.17152261, 0.83530153, 0.70537941, 0.08963202, 0.36817803]])

In [ ]:
B=np.array([[1,2,3],[1,2,1]])

In [ ]:
B_SVD=np.linalg.svd(B)

In [ ]:
sigma=np.diag(B_SVD[1])
sigma

array([[4.3525018, 0.       ],
       [0.       , 1.0274863]])

In [ ]:
sigma2=np.concatenate([sigma,np.zeros((2,1))],axis=1)

In [ ]:
sigma2

array([[4.3525018, 0.       , 0.       ],
       [0.       , 1.0274863, 0.       ]])

In [ ]:
B_SVD[0] @ sigma2 @ B_SVD[2]

array([[1., 2., 3.],
       [1., 2., 1.]])

#### Zadanie
Oblicz $\begin{bmatrix} 1&2&3\\1&2&1\\0&1&0\end{bmatrix}^{20}$.

In [ ]:
A=np.array([[1,2,3],[1,2,1],[0,1,0]])

In [ ]:
%time np.linalg.matrix_power(A,20)

CPU times: user 90 µs, sys: 8 µs, total: 98 µs
Wall time: 101 µs


array([[16968908951, 41687151125, 26786952325],
       [14535850675, 35709909551, 22946150525],
       [ 4205149925, 10330700750,  6638208201]])

In [ ]:
%%time
A_rozklad=np.linalg.eig(A)
JA=np.diag(A_rozklad[0])
P=A_rozklad[1]
P @ JA**20 @ np.linalg.inv(P)


CPU times: user 571 µs, sys: 0 ns, total: 571 µs
Wall time: 540 µs


array([[ 3.45667834+0.j        ,  0.        +0.j        ,
         0.        +0.j        ],
       [ 0.        +0.j        , -0.22833917+0.72556968j,
         0.        +0.j        ],
       [ 0.        +0.j        ,  0.        +0.j        ,
        -0.22833917-0.72556968j]])

In [ ]:

P

array([[ 0.74635087+0.j        , -0.85289345+0.j        ,
        -0.85289345-0.j        ],
       [ 0.63933662+0.j        ,  0.21479077+0.23188188j,
         0.21479077-0.23188188j],
       [ 0.18495693+0.j        ,  0.20602029-0.36086579j,
         0.20602029+0.36086579j]])

## Rozwiązywanie układów równań

* ```np.linalg.cond``` - wskaźnik uwarunkowania
* ```np.linalg.solve``` - rozwiązywanie

In [ ]:
np.linalg.cond(A)

11.87432495287239

SyntaxError: ignored

#### Zadanie 
Oblicz współczynnik uwarunkowania i rozwiąż układ równań $Ax=b$.

$$
A=\begin{bmatrix} 1&0&2\\3&2&1\\1&1&1 \end{bmatrix},\quad b_1=\begin{bmatrix}20.001\\-9.9999\\ 100.00001\end{bmatrix},\quad  b_2=\begin{bmatrix}20\\-10\\ 100\end{bmatrix}
$$

In [20]:
A=np.array([[1,0,2],[3,2,1],[1,1,1]])

In [21]:
np.linalg.cond(A)

10.617346008950063

In [22]:
b1=np.array([20.001,-9.9999,100.00001])
b2=np.array([20,-10,100])

In [23]:
np.linalg.solve(A,b1)

array([-133.33294667,  156.66598333,   76.66697333])

In [24]:
np.linalg.solve(A,b2)

array([-133.33333333,  156.66666667,   76.66666667])

### Zadanie domowe
Stowrzyć macierz 3x3 o współczynniku uwarunkowania co najmniej $10000$ i sprawdzić błąd rozwiązania dla b1 i b2

In [4]:
import numpy as np
A=np.array([[1,13131,2],[3,2,1],[1,1,1]])
b1=np.array([20.001,-9.9999,100.00001])
b2=np.array([20,-10,100])
np.linalg.cond(A)

22416.696852644556

In [42]:
np.linalg.solve(A,b1)

array([-5.49910057e+01, -1.78985472e-02,  1.55008914e+02])

In [43]:
np.linalg.solve(A,b2)

array([-5.49910507e+01, -1.78986252e-02,  1.55008949e+02])

#### Zadanie dla chętnych (łańcuch Markowa)
$P=\begin{bmatrix} 1&0&0&0&0&0\\0&1&0&0&0&0\\p&q&r&0&0&0\\p&0&q&r&0&0\\p&0&0&q&r&0\\p&0&0&0&q&r \end{bmatrix}$



Macierz P opisuje prawdopodobieństwa przejść między pięcioma stanami: wyrzucony ze studiów, ukończył studia, po 4 roku, po 3 roku, po 2 roku, po 1 roku. (np. ze stanu nr 6 do stanu nr 5 prawdop. = q). Przyjmijmy p=0.2, q=0.7, r=0.1.

* Oblicz prawdopodobieństwo, że jeśli ukończyłeś pierwszy rok, to ukończysz całe studia.

* Zauważ w macierzy $P$ blokową strukturę: $P=\begin{bmatrix} Id & 0 \\ R & Q \end{bmatrix}$. Porównaj poprzedni wynik z wynikiem mnożenia $(Id-Q)^{-1} R$.